#! /bin/bash
CUDA_HOME=/usr/local/cuda

# Check if the CUDA home directory exists
if [ -d "$CUDA_HOME" ]; then
    echo "CUDA home directory: $CUDA_HOME"
else
    echo "Error: CUDA home directory does not exist: $CUDA_HOME" >&2
    exit 1
fi

printf "Building... "

nvcc -shared -o libsegcumsum.so -O3 --compiler-options '-O3 -fPIC' segcumsum.cu -lcudart -I$CUDA_HOME/targets/x86_64-linux/include -L$CUDA_HOME/targets/x86_64-linux/lib \
    -gencode arch=compute_50,code=sm_50 \
    -gencode arch=compute_52,code=sm_52 \
    -gencode arch=compute_60,code=sm_60 \
    -gencode arch=compute_61,code=sm_61 \
    -gencode arch=compute_70,code=sm_70 \
    -gencode arch=compute_75,code=sm_75 \
    -gencode arch=compute_80,code=sm_80 \
    -gencode arch=compute_86,code=sm_86

printf "done\n\n"


# nvcc -shared -o libsegcumsum.so -O3 --compiler-options '-O3 -fPIC' segcumsum.cu -l cudart -I/home/talamir/.miniconda3/envs/swembedding/lib/python3.12/site-packages/nvidia/cuda_runtime/include -L/usr/local/cuda/targets/x86_64-linux/lib \
#     -gencode arch=compute_50,code=sm_50 \
#     -gencode arch=compute_52,code=sm_52 \
#     -gencode arch=compute_60,code=sm_60 \
#     -gencode arch=compute_61,code=sm_61 \
#     -gencode arch=compute_70,code=sm_70 \
#     -gencode arch=compute_75,code=sm_75 \
#     -gencode arch=compute_80,code=sm_80 \
#     -gencode arch=compute_86,code=sm_86

